- name: Check that you can connect on octo-spy
  uri:
    url: "{{ octo_spy_host }}/info"

- name: Register deployment
  uri:
    url: "{{ octo_spy_host }}/deployment"
    method: POST
    body: "{{ lookup('template', './deployment.json.j2') }}"
    status_code: 201,400
    body_format: json
    return_content: yes
  register: result

- name: Register project on octo-spy
  uri:
    url: "{{ octo_spy_host }}/project"
    method: POST
    body: "{\"name\":\"{{ project_name }}\"}"
    body_format: json
    status_code: 201
  when: result.json.message == "Field value is bad." and result.json.field == "project"

- name: Register deployment with new register project on octo-spy
  uri:
    url: "{{ octo_spy_host }}/deployment"
    method: POST
    body: "{{ lookup('template', './deployment.json.j2') }}"
    status_code: 201
    body_format: json
  when: result.json.message == "Field value is bad." and result.json.field == "project"
