- name: Check that you can connect on octo-spy
  uri:
    url: "{{ octo_spy_host }}/info"

- name: Register deployment
  uri:
    url: "{{ octo_spy_host }}/deployment"
    url_username: "{{ octo_username }}"
    url_password: "{{ octo_password }}"
    method: POST
    body: "{{ lookup('template', './deployment.json.j2') }}"
    status_code: 201,400,404
    body_format: json
    return_content: yes
  register: result
  when: step == "start"

- name: Register project on octo-spy
  uri:
    url: "{{ octo_spy_host }}/project"
    url_username: "{{ octo_username }}"
    url_password: "{{ octo_password }}"
    method: POST
    body: "{\"name\":\"{{ project_name }}\"}"
    body_format: json
    status_code: 201
  when: step == "start" and result.status == 404 and result.json.field == "project"

- name: Register deployment with new register project on octo-spy
  uri:
    url: "{{ octo_spy_host }}/deployment"
    url_username: "{{ octo_username }}"
    url_password: "{{ octo_password }}"
    method: POST
    body: "{{ lookup('template', './deployment.json.j2') }}"
    status_code: 201
    body_format: json
  when: step == "start" and result.status == 404 and result.json.field == "project"

- name: Delete progress of deployment
  uri:
    url: "{{ octo_spy_host }}/deployment/progress"
    url_username: "{{ octo_username }}"
    url_password: "{{ octo_password }}"
    method: DELETE
    body: "{{ lookup('template', './progress.json.j2') }}"
    status_code: 204
    body_format: json
  when: step == "end"

